/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class App */

#ifndef _Included_App
#define _Included_App
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     App
 * Method:    add
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_App_add
  (JNIEnv *, jobject, jint);

/*
 * Class:     App
 * Method:    print
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_App_print
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
